spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

upload:
  path: ./log