spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
