name: CI
on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: burrunan/gradle-cache-action@v1
        name: Cache .gradle

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: burrunan/gradle-cache-action@v1
        name: Cache .gradle

      - name: Set up Gradle Permission
        run: chmod +x ./gradlew

#      - name: Publish Spotbugs Results
#        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
#        with:
#          name: Spotbugs
#          path: build/reports/spotbugs/*.xml
#
#      - name: Publish Sonarlint Results
#        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
#        with:
#          name: Sonarlint
#          title: Sonarlint report
#          path: build/reports/sonarlint/*.xml

      - name: Build
        run: ./gradlew -s build -x test

